name: ci
on:
  push:
    paths-ignore:
      - 'docs/**'
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ github.ref }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Install mkdocs with plugins
        run: pip install mkdocs-material
      # usually you use gh-deploy, but we want this in a subfolder instead of the whole github page
      # thus we manually build and then deploy that
      - name: build documentation
        run: mkdocs build --clean
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: commit
        run: |
          git add docs
          git commit -m "Updated docs using build"
          git push origin main
